traveler:
  type: "object"
  properties:
    - age:
        type: "number"
    - last_name:
        type: "string"
    - name:
        type: "string"
    - id:
        type: "string"
  required:
    - "age"
    - "last_name"
    - "name"
    - "id"
travelerOpt:
  type: "object"
  properties:
    - last_name:
        type: "string"
    - name:
        type: "string"
    - id:
        type: "string"
    - age:
        type: "number"
        description: "Age of the traveler"
  required:
    - "last_name"
    - "name"
    - "id"
